### PR TITLE
feat: add Simple-Finder app

### PR DESCRIPTION
**Pull request by seniya**
Hi
Introduce the 'Simple-Finder' app

This application is a basic function of file finder. The purpose of this application is to see the basic functions and possibilities of Electron through a relatively simple project.

Thank you for your help.

URL : https://github.com/seniya/electron-finder-normal

98706494-3ed97b80-23c2-11eb-8bed-543a5acc9a7a

### CODE REVIEW

**Comment by dstiers11** [comment]
Hi

**Comment by dstiers11** [comment]
>

**Comment by seniya** [comment]
> Hi

Hi

**Comment by Toinane** [comment]
Hey @seniya thank you for your app! It looks good to me 👍

**Pull request merged**
