### PR TITLE
feat: add Geniemoji app

### PR DESCRIPTION
**Pull request by virejdasani**
### Checklist

- [x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [x] My application is open-source and has been created for at least 20 days
- [ ] My application is closed-source and here is a proof it uses Electron:

### Description
- [Geniemoji](https://github.com/virejdasani/Geniemoji) is an open-source, Electron app that makes using Emoji on desktop easier than ever!
- Check out the website [here](https://virejdasani.github.io/Geniemoji/)
- Check it out on YouTube [here](https://www.youtube.com/watch?v=0I18p8e1Z5Y)

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @virejdasani thank you for your application! Can you remove the package-lock file from your PR? Thank you 👍

**Comment by virejdasani** [comment]
Done!

**Comment by Toinane** [comment]
Arh, you deleted the file from project and not just from your PR. Don't worry I'll make a new one without this issue

**Comment by Toinane** [comment]
Done in #1801

**Comment by virejdasani** [comment]
Thanks a lot!!

**Pull request closed without merging**
