### PR TITLE
feat: Add Elephicon app

### PR DESCRIPTION
**Pull request by sprout2000**
Hello.  
I made a tiny tool for ICO and ICNS files.  

**repository:** https://github.com/sprout2000/elephicon
**website:** https://sprout2000.github.io/elephicon/

**screenshot:**
screenshot 2020-06-04 6 56 07

Best regards.

### CODE REVIEW

**Comment by sprout2000** [comment]
@HashimotoYT Thank you for your reviewing.
I will open another PR.

**Comment by Toinane** [comment]
Hey @sprout2000 if you still want to add this application, can you remove the update files from the other application?

**Comment by sprout2000** [comment]
@Toinane 
I'm sorry but I withdraw this proposal.

**Comment by Toinane** [comment]
No problem 👍

**Pull request closed without merging**
