### PR TITLE
fix: Update luna.yml

### PR DESCRIPTION
**Pull request by rvpanoz**
update luna metadata

- description
- imageUrl
- keywords
- category

### CODE REVIEW

**Comment by barbhackk** [comment]
I,
It's necessary to add a conventional commit types on your title for completed all requisites.
Exemple : fix: Update luna.yml

Barbhackk

**Comment by rvpanoz** [comment]
ok! thank you. I will update it soon

**Comment by rvpanoz** [comment]
> I,
> It's necessary to add a conventional commit types on your title for completed all requisites.
> Exemple: **fix:** Update luna.yml
> 
> Barbhackk

Title updated. :)

**Comment by barbhackk** [comment]
> > I,
> > It's necessary to add a conventional commit types on your title for completed all requisites.
> > Exemple: **fix:** Update luna.yml
> > Barbhackk
> 
> Title updated. :)

'Update' is not accepted. Please see this link : [https://github.com/commitizen/conventional-commit-types/blob/master/index.json](https://github.com/commitizen/conventional-commit-types/blob/master/index.json)

**Comment by rvpanoz** [comment]
updated :)

**Comment by rvpanoz** [comment]
You are welcome ;) @ckerr

**Pull request merged**
