### PR TITLE
feat: Add znote app

### PR DESCRIPTION
**Pull request by alagrede**
Hello,

I would like share with the community my last Electron app: **Znote**. 
A **Free & beautiful** Markdown editor, built to secure your text files.

*Available on Mac/Windows Stores.*

Thanks for your work.

**Website**
[znote.lagrede.fr](https://znote.lagrede.fr)

**Repository**
[alagrede/znote-app](https://github.com/alagrede/znote-app)

**Screenshots**
screenshot

**Znote is a closed source app, so here's some evidence of the Electron part:**

Screenshot of the app in development mode with Electron warnings:
https://znote.lagrede.fr/assets/custom/img/znote-electron.png

My dev.to post explaining how I build and deploy this app:
https://dev.to/alagrede/i-succeed-to-publish-my-first-electron-app-on-apple-store-1a7n

The credit showing technologies used on the github repo where I publish all releases:
https://github.com/alagrede/znote-app/blob/master/README.md
https://github.com/alagrede/znote-app/releases/tag/v0.3.5

### CODE REVIEW

**Comment by alagrede** [comment]
Hello,
Thanks for your review. I added a section at the end of the Readme.md: build with Electron & React
https://github.com/alagrede/znote-app
I hope this update will meet your requirements.
Sincerely

**Comment by alagrede** [comment]
> Looks like this app is closed source. As per the [submission guidelines](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines), could you provide some evidence that this is an Electron app? [Previous PRs](https://github.com/electron/apps/pulls?utf8=%E2%9C%93&q=is%3Apr+evidence) are a good source for what other apps have used as evidence. Thanks!

Hello, as recommended I updated the section to add Electron evidences.
Thank you very much.

**Comment by Toinane** [comment]
Hey @alagrede Thank you for your application.
Sorry for the misunderstanding, we need a screenshot or video that prove you use Electron in your application, like the package.json for example.
Can you add here the proof of Electron use? Thanks!

**Comment by alagrede** [comment]
> Hey @alagrede Thank you for your application.
> Sorry for the misunderstanding, we need a screenshot or video that prove you use Electron in your application, like the package.json for example.
> Can you add here the proof of Electron use? Thanks!

Hello @Toinane,
What's about links provided below?

Screenshot of the app in development mode with Electron warnings:
https://znote.lagrede.fr/assets/custom/img/znote-electron.png

My dev.to post explaining how I build and deploy this app:
https://dev.to/alagrede/i-succeed-to-publish-my-first-electron-app-on-apple-store-1a7n

The credit showing technologies used on the github repo where I publish all releases:
https://github.com/alagrede/znote-app/blob/master/README.md
https://github.com/alagrede/znote-app/releases/tag/v0.3.5

**Comment by Toinane** [comment]
Hey @alagrede thank you for your response! Its now ok for us, thank you! 👍

**Pull request merged**
