### PR TITLE
feat: Update Picturama screenshot URL

### PR DESCRIPTION
**Pull request by til-schneider**
The old screenshot URL won't work any more

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @til-schneider Thank you for the update! Can you resolve the semantic commit issue before merging?

**Comment by til-schneider** [comment]
I don't know what to do. Do you want me to change the commit message to start with `feat:`?

**Comment by Toinane** [comment]
Yeah or just add a new commit to allow me to squash it

**Comment by til-schneider** [comment]
Done.

**Comment by Toinane** [comment]
Awesome! It's good to me 👍

**Pull request merged**
