### PR TITLE
feat: add Stinker

### PR DESCRIPTION
**Pull request by PatentLobster**
### Checklist

- [ x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [ x] My application is open-source and has been created for at least 20 days

### Description

# Stinker
Laravel tinker snippet app.

screenshot

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @PatentLobster thank you for your application! Looks good to me 👍

**Comment by Toinane** [comment]
Ah, you need to change your logo's name to "stinker-icon.png"

**Comment by PatentLobster** [comment]
Thank you @Toinane, I've changed the logo name hopefully should be good now :)

**Comment by Toinane** [comment]
Thanks! 👍

**Pull request merged**
