### PR TITLE
feat: Add Master Tour

### PR DESCRIPTION
**Pull request by sators**
Adding [Master Tour](https://www.eventric.com/master-tour-management-software/) to Electron App directory. [https://www.eventric.com/master-tour-management-software/](https://www.eventric.com/master-tour-management-software/)
Dashboard View
Guest List Management
Schedule View

### CODE REVIEW

**Comment by ckerr** [comment]
Looks like this app is closed source. As per the [submission guidelines](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines), could you provide some evidence that this is an Electron app? [Previous PRs](https://github.com/electron/apps/pulls?utf8&#x3D;%E2%9C%93&amp;q&#x3D;is%3Apr+evidence) are a good source for what other apps have used as evidence. Thanks!

**Comment by sators** [comment]
Hello - below you will find the evidence that the app is created with Electron, a screenshot with the devtools displaying the Electron Security Warnings (details of warning cropped out)

Thanks!

Screen Shot 2020-05-14 at 9 14 03 PM

**Comment by sators** [comment]
This has been moved to a user based repository.

**Comment by HashimotoYT** [comment]
@sators Could you please allow edit this pull request for maintainers. You can do that in the pull request sidebar:

need edit rights

**Comment by sators** [comment]
Done!

**Comment by Toinane** [comment]
Hey @sators thank you for your application ! 
It seem that i cant update your branch, Can you give me Access to it or update it in order to merge it?

Thank you 👍

**Comment by sators** [comment]
Added @Toinane!

**Comment by Toinane** [comment]
@sators thanks! its now all good! 👍

**Pull request merged**
