### PR TITLE
feat: Add He3 App

### PR DESCRIPTION
**Pull request by hongchaodeng**
### Checklist

- [X] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [ ] My application is open-source and has been created for at least 20 days
- [X] My application is closed-source and here is a proof it uses Electron:

Snipaste_2022-11-19_14-45-33

### Description

[He3](https://he3.app/)  is a free developer toolbox that boosts developer productivity. It provides 200 builtin utility tools with more to come. It comes with convenient features like smart search, auto detection, hotkeys, etc.

Here is a blog describing He3 in more details: https://he3.app/posts/announcement_en/

### CODE REVIEW

**Comment by BlackHole1** [comment]
Hi @hongchaodeng . CI failed, can you fix it?

**Comment by hongchaodeng** [comment]
@BlackHole1 
Thanks for reminding me. Just fixed. I used "he3.yaml" but it should be "he3.yml" 🤣

**Comment by BlackHole1** [comment]
@hongchaodeng CI failed again.

**Comment by hongchaodeng** [comment]
@BlackHole1 Fixed. Please approve to run the workflow :)

**Pull request merged**
