### PR TITLE
Add AccuMap

### PR DESCRIPTION
**Pull request by EoinAviation**
AccuMap is a modern, snazzy and intuitive desktop application for viewing live VATSIM data such as pilots and air traffic controllers.

### CODE REVIEW

**Comment by codebytere** [comment]
ignore the accidental approve, sorry!

**Comment by EoinAviation** [comment]
Failed again 😢

**Comment by codebytere** [comment]
@EoinAviation two errors:
1) icon must be at least 128px x 128px (yours is too small()
2) screenshot imageUrl must be a fully-qualified HTTPS URL (yours is http)

**Comment by vanessayuenn** [comment]
_bump @EoinAviation_

**Pull request closed without merging**
