### PR TITLE
feat: Added my app Flawesome

### PR DESCRIPTION
**Pull request by ashishBharadwaj**
App: Flawesome
Website: https://github.com/ashishBharadwaj/flawesome
Github Repo: https://github.com/ashishBharadwaj/flawesome

Screenshots:

ScreenShotsTab1
ScreenShotTab2
ScreenShotTab3

### CODE REVIEW

**Comment by ashishBharadwaj** [comment]
I am not sure who to add as a reviewer! Adding @HashimotoYT . Would you please review this PR and merge if everything looks good?

**Comment by Toinane** [comment]
You should make at least one home page, Electron allows a good referencing, it would be a waste not to take advantage of it and it can make bad publicity to have a non-functional link. 👍

**Comment by ashishBharadwaj** [comment]
I have plans to make this app available as web version as well. Work for that is in progress! The link would remain same though!! Would i be allowed to publish the app mean while ?

**Comment by Toinane** [comment]
I'm not in charge of PR on this repo, but in my opinion, I'm afraid it won't pass. The best would be to link to the repo github and then make a new PR to update the link when the site is working.

**Comment by ashishBharadwaj** [comment]
I just updated the website in code and in PR. I will add the link once the website is up and running..!
Can you approve and merge this PR..?

**Comment by ashishBharadwaj** [comment]
@Toinane Man can you at least tell me what is the process for getting a reviewer for PR in this repo? Or how long would i have to wait for this to be merged? Looks like you are a member of Electron community! Some help would be really appreciated here!

**Comment by Toinane** [comment]
> 
> 
> @Toinane Man can you at least tell me what is the process for getting a reviewer for PR in this repo? Or how long would i have to wait for this to be merged? Looks like you are a member of Electron community! Some help would be really appreciated here!

As I said before, I'm not in charge of pull requests here. You have to wait for the reply from @HashimotoYT for that. Maybe I can become a reviewer to handle the pull request pile, What do you think about it Vlad?

**Comment by ashishBharadwaj** [comment]
> 
> 
> > @Toinane Man can you at least tell me what is the process for getting a reviewer for PR in this repo? Or how long would i have to wait for this to be merged? Looks like you are a member of Electron community! Some help would be really appreciated here!
> 
> As I said before, I'm not in charge of pull requests here. You have to wait for the reply from @HashimotoYT for that. Maybe I can become a reviewer to handle the pull request pile, What do you think about it Vlad?

Thanks for replying man! It looks like there nothing that can be done other than wait :(

**Comment by Toinane** [comment]
> 
> 
> > > @Toinane Man can you at least tell me what is the process for getting a reviewer for PR in this repo? Or how long would i have to wait for this to be merged? Looks like you are a member of Electron community! Some help would be really appreciated here!
> > 
> > 
> > As I said before, I'm not in charge of pull requests here. You have to wait for the reply from @HashimotoYT for that. Maybe I can become a reviewer to handle the pull request pile, What do you think about it Vlad?
> 
> Thanks for replying man! It looks like there nothing that can be done other than wait :(

Yeah sorry, I'm also waiting for my PR here :)

**Comment by ashishBharadwaj** [comment]
@ckerr Can you please review this PR?

**Comment by ashishBharadwaj** [comment]
@ckerr Can you please help me out here I have been waiting for a long time for this PR to be merged :(

**Pull request merged**
