### PR TITLE
feat: Add Stacks app

### PR DESCRIPTION
**Pull request by synapse**

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @synapse thank you for your application!
As your app is closed source, we need to have a proof that its build with Electron, It can be a screenshot 👍 
Thank you!

**Comment by synapse** [comment]
Hey @Toinane here's the screenshot:



here is also the website where you can view more screenshots and download the app: https://stacks.rocks

**Comment by Toinane** [comment]
Hey @synapse I'm sorry but its not actually a proof that your app use Electron. You can show the development tool or the package.json with Electron to prove it.

You can check this PR as example #1501

**Comment by synapse** [comment]
Hey @Toinane yeah sorry, I updated the previous post and added the correct screenshot

**Comment by Toinane** [comment]
No worries 😀 its now good to me!

**Pull request merged**
