### PR TITLE
feat: added Racompass app

### PR DESCRIPTION
**Pull request by appsnano**
### Checklist

- [x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [x] My application is closed-source and here is a proof it uses Electron:
- [ ] My application is open-source and has been created for at least 20 days

### Proof
for-electron-apps

### Description
Racompass is a modern high performance GUI for Redis.
Supported Connections: Standalone,Sentinel,Cluster.
Supported Data Types: String,List,Set,Hash,Sorted Set,Stream.
It supports Redis 6!!!
[Available for Mac.](https://apps.apple.com/app/id1538380685)

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @appsnano thank you for your app! Can you change your logo's name and add "-icon" at end? And update your branch from master or allow me to do it? Thank you 👍

**Comment by Toinane** [comment]
Hey @appsnano you just need to update the icon's name 👍

**Comment by appsnano** [comment]
Hi @Toinane,
I updated logo's name and added "-icon" at en "racompass-icon.png".
Thank you~!

Screenshot 2021-05-31 at 21 30 07

**Comment by Toinane** [comment]
> 
> 
> Hi @Toinane,
> I updated logo's name and added "-icon" at end "racompass-icon.png".
> Thank you~!
> 
> Screenshot 2021-05-31 at 21 30 07

Its actually "racompass-logo.png" and should be "racompass-icon.png" the CI build failed because of that

**Comment by Toinane** [comment]
Thank you @appsnano! It looks now good 👍

**Comment by appsnano** [comment]
oh, 😳 sorry about that.
i updated the correct one.
Thank you @Toinane ~!!!!

**Pull request merged**
