### PR TITLE
feat: catalyst web browser

### PR DESCRIPTION
**Pull request by JaydenDev**
### Checklist

:ballot_box_with_check:   I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
:ballot_box_with_check: My application is open-source and has been created for at least 20 days
:x: My application is closed-source and here is a proof it uses Electron:

### Description

This... is the Catalyst web browser. A not-so-bleeding-edge browser with not so many features. But, if there's any feature I should mention here It's complete privacy, plentiful customization, and a fresh UI designed in tailwind. This browser will take a little over 128 MB of RAM with lots of tabs open. Made with Electron/Chromium WebView technologies. A fully open source web browser with code YOU, the user can read with ease. Enjoy!

### Screenshot
image

### Binaries can be found at:
https://github.com/JaydenDev/Catalyst/releases \
Windows, MacOS, and Linux releases for both 32 bit and 64 bit are available.
### Screenshots and README @ 
https://github.com/JaydenDev/Catalyst/tree/main/README.md

### CODE REVIEW

**Comment by JaydenDev** [comment]
I'm adding a screenshot soon!

**Comment by JaydenDev** [comment]
Are there any requirements this does not yet meet?

**Comment by JaydenDev** [comment]
Please tell me what "more info" is required

**Comment by JaydenDev** [comment]
@Toinane If a longer description is what was needed I added a longer description

**Comment by Toinane** [comment]
Hey @JaydenDev sorry, I was away more longer as espected. You need to add '-icon' in the end's name of your icon.
Just add a dot at the end of your description.
And the last one, use a correct category from here: https://github.com/electron/apps/blob/master/contributing.md#categories
thank you! 👍

**Comment by JaydenDev** [comment]
@Toinane I renamed the icon and added a correct category

**Comment by Toinane** [comment]
Thank you @JaydenDev ! It should be good now

**Comment by JaydenDev** [comment]
The build failed, something to do with the icon. Unfortunately that might be the only icon i have.

**Comment by Toinane** [comment]
Okay, so one last thing, is your icon is too big, it should be between 256px x 256px and 1024px x 1024px

**Comment by JaydenDev** [comment]
> Okay, so one last thing, is your icon is too big, it should be between 256px x 256px and 1024px x 1024px

i'll ask the designer of the icon to make a version at that scale

**Comment by Toinane** [comment]
catalyst-icon

**Comment by Toinane** [comment]
here your icon at a good scale (i'm also designer)

**Comment by JaydenDev** [comment]
Compatible icon added, build requested.

**Comment by Toinane** [comment]
It's now okay, thank you again!

**Pull request merged**
