### PR TITLE
feat: 'Add Demoflow'

### PR DESCRIPTION
**Pull request by lucasbaze**

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @lucasbaze Thank you for your application!
Looks like this app is closed source. As per the [submission guidelines](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines), could you provide some evidence that this is an Electron app? [Previous PRs](https://github.com/electron/apps/pulls?utf8=%E2%9C%93&q=is%3Apr+evidence) are a good source for what other apps have used as evidence. Thanks!

**Comment by Toinane** [comment]
Also, your website seem to be offline, I can't reach it.

**Comment by lucasbaze** [comment]
My apologies! Will get that to you asap!

**Comment by lucasbaze** [comment]
Fixed the links... guess our redirect isn't working. Thanks for catching that!

Will this work? 
Screen Shot 2020-08-06 at 12 48 16 PM

Screen Shot 2020-08-06 at 12 51 43 PM

**Comment by Toinane** [comment]
Hey @lucasbaze thank you for the update! Its now look good to me 👍

**Pull request merged**
