### PR TITLE
feat: Add WebKitty app

### PR DESCRIPTION
**Pull request by yikuansun**
:cat:

### Checklist

- [x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [x] My application is open-source and has been created for at least 20 days
- [ ] My application is closed-source and here is a proof it uses Electron:

### Description

https://github.com/yikuansun/webkitty

WebKitty is a lightweight native HTML IDE for web developers of any level. It utilizes webview for a powerful side-by-side text editor and preview.
App Screenshot

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @yikuansun thank you for your app!
can you edit your icon's name? it should contains '-icon' at the end.

**Comment by yikuansun** [comment]
Hi @Toinane , I don't quite understand, sorry about that. The icon I'm committing is named `webkitty-icon.png`, what do you suggest I change it to?

**Comment by Toinane** [comment]
Woups, sorry wrong comment here!

**Comment by yikuansun** [comment]
@Toinane Thanks!

**Pull request merged**
