### PR TITLE
feat: Update Inkdrop

### PR DESCRIPTION
**Pull request by craftzdog**
Hello there,

I would like to update my app Inkdrop to the latest information.
Thanks for taking your time!

P.S. I've written a blogpost about [how to use v8 snapshots to improve your Electron app launch speed](https://blog.inkdrop.info/how-to-make-your-electron-app-launch-1000ms-faster-32ce1e0bb52c).

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @craftzdog thank you for the update! Can you allow maintainers edits on your PR? And I also need you to resolve the semantic issue, I'll merge it after that 👍

**Comment by craftzdog** [comment]
Hi, thanks for reviewing it!
Sure, but how can I give you the edit permission? I can't find "[Allow edits from maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)" on the sidebar.

Screen Shot 2020-09-08 at 22 06 45

**Comment by Toinane** [comment]
ah strange, no problem so, can you edit your commit and add "feat:" before your commit message?

**Comment by craftzdog** [comment]
done!

**Comment by Toinane** [comment]
Good! Can you update your branch with the base branch? you have the button here

**Comment by Toinane** [comment]
Thank you @craftzdog 👍  Its now good to me! And sorry for the manipulation

**Comment by craftzdog** [comment]
Thank you!

**Pull request merged**
