### PR TITLE
feat: add AnimeBack

### PR DESCRIPTION
**Pull request by LeGitHubDeTai**
### Name
AnimeBack

### Description
Anime your wallpaper.

### Website
https://legithubdetai.github.io/AnimeBack/

### Screenshot
</img>
### Trailer/Video
https://www.youtube.com/watch?v=JpFKSTRth4M

### CODE REVIEW

**Review by ckerr — COMMENTED** [review]
Hey @LeGitHubDeTai thank you for your app submission!
Please, if your application is a closed source app, can you remove the "repository" field in the yaml and as per the [submission guidelines](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines), could you provide some evidence that this is an Electron app? [Previous PRs](https://github.com/electron/apps/pulls?utf8=%E2%9C%93&q=is%3Apr+evidence) are a good source for what other apps have used as evidence.

**Comment by LeGitHubDeTai** [comment]
image

**Comment by LeGitHubDeTai** [comment]
image

**Review by ckerr — APPROVED** [review]
Thanks!

**Pull request merged**
