### PR TITLE
feat: Added Passky

### PR DESCRIPTION
**Pull request by zigazajc007**
### Checklist

- [x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [x] My application is open-source and has been created for at least 20 days
- [ ] My application is closed-source and here is a proof it uses Electron:

### Description
Passky is simple password manager, which works on a zero trust architecture. That means only user will be able to decrypt his passwords. So users can safely store their passwords on any server. That means if a server on where all passwords are stored get hacked, hacker won't be able to decrypt passwords and data on this server will be useless for him.

Pictures are available on Snapcraft: https://snapcraft.io/passky

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @zigazajc007 thank you for your application! Can you rebase it from master or allow me to update it?
Thank you 👍

**Comment by zigazajc007** [comment]
Hello, you can update it.

**Comment by Toinane** [comment]
the button is disabled on my side sorry

**Comment by zigazajc007** [comment]
Sorry, but I don't understand what you mean.

**Comment by Toinane** [comment]
I can't click on the button "Squash and merge" because I can't edit your PR actually to make automatic rebase. So you can check "allow maintainer to edit your PR" or just rebase your branch from master 👍

**Comment by zigazajc007** [comment]
Sorry, but I can't find "allow maintainer to edit your PR" checkbox.

**Comment by Toinane** [comment]
hmm strange, so can you just rebase your branch in this case?

**Comment by Toinane** [comment]
here the guide for allow maintainer: [https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by zigazajc007** [comment]
I don't know a lot about advanced GitHub features. So it would be better if I just create new pull request.

**Comment by Toinane** [comment]
it will not change much, you need to rebase your branch from master, you can follow theses git command to do that easely: [https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a](https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a)

**Comment by zigazajc007** [comment]
Do I need to do that for my Password manager (Rabbit-Company/Passky-Desktop) or your electron / apps?

**Comment by Toinane** [comment]
on your fork of electron/apps

**Comment by zigazajc007** [comment]
I have deleted it from my GitHub as I don't like to have any forks on my account.

**Comment by zigazajc007** [comment]
I can fork it again

**Comment by Toinane** [comment]
ah! Indeed so you need to make a new PR sorry :/

**Comment by zigazajc007** [comment]
Here you go: https://github.com/electron/apps/pull/1836

**Pull request closed without merging**
