### PR TITLE
feat: Add Sigma File Manager

### PR DESCRIPTION
**Pull request by aleksey-hoffman**
### Checklist

- [x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [x] My application is open-source and has been created for at least 20 days
- [ ] My application is closed-source and here is a proof it uses Electron:

### Description
https://github.com/aleksey-hoffman/sigma-file-manager

"Sigma File Manager" is a free, open-source, quickly evolving, modern file manager (explorer / finder) app for Windows and Linux.

### CODE REVIEW

**Comment by aleksey-hoffman** [comment]
@erickzhao hey mate, is there something wrong with this PR?

**Comment by aleksey-hoffman** [comment]
@BlackHole1 hey mate, is there something wrong with this PR? It was created 3 months ago and there's still no feedback

**Review by BlackHole1 — APPROVED** [review]
Look great! 👍
I apologize for responding only now, as I have a lot of emails and sometimes I may miss some messages. 🙇‍♂️

**Comment by aleksey-hoffman** [comment]
@BlackHole1 thanks you!

**Comment by aleksey-hoffman** [comment]
@BlackHole1 by the way, do you know how long it takes for a newly added app to appear on the website? 
I cannot find it there right now

image

**Comment by BlackHole1** [comment]
@aleksey-hoffman See: https://github.com/electron/apps/issues/2058#issuecomment-1244808039

**Pull request merged**
