### PR TITLE
feat: Add 'Dynobase' app 

### PR DESCRIPTION
**Pull request by RafalWilinski**
App link: https://dynobase.dev

Screenshots:

https://dynobase.s3.amazonaws.com/listings/electronjs/dynamodb-gui-client-1.png
https://dynobase.s3.amazonaws.com/listings/electronjs/dynamodb-gui-client-2.png
https://dynobase.s3.amazonaws.com/listings/electronjs/dynamodb-gui-client-3.png
https://dynobase.s3.amazonaws.com/listings/electronjs/dynamodb-gui-client-4.png

### CODE REVIEW

**Comment by scris** [comment]
Well, it seems to be a closed-source app, https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines says that you may need to give some evidences to prove this app is built with electron. :)

**Comment by RafalWilinski** [comment]
Screenshot 2020-03-02 at 22 17 45

Here's Dynobase ran in dev mode with Developer Tools opened, warning related to ElectronJS is displayed.

**Comment by HashimotoYT** [comment]
@RafalWilinski  Please allow editing this pull request from maintainers for easily merging this PR.

You can do this from PR sidebar:

Untitled

**Comment by RafalWilinski** [comment]
@HashimotoYT I had to move repo from my org to my personal account in order to enable that option but managed to that without issues. "Allow edits from maintainers" is now checked.

**Pull request merged**
