### PR TITLE
feat: add drawtify designer app;

### PR DESCRIPTION
**Pull request by brucesong08**
name: Drawtify Designer
description:
  Full-featured graphic design software, publisher, animator & vector editor.
website: https://drawtify.com/drawtify-designer/
category: 'Graphics & Design'
youtube_video_url: https://youtu.be/4KKxVqbcGLw
screenshots:
  - imageUrl: 'https://drawtify.com/wp-content/uploads/2020/11/drawtify-designer-app-photo-3.png'
    caption: 'powerful vector editor'
    imageLink: 'https://drawtify.com/drawtify-designer/'
  - imageUrl: 'https://drawtify.com/wp-content/uploads/2020/11/drawtify-designer-app-photo-6-1.png'
    caption: 'powerful art text'
    imageLink: 'https://drawtify.com/feature'
  - imageUrl: 'https://drawtify.com/wp-content/uploads/2020/11/drawtify-designer-app-photo-5-1.png'
    caption: 'easy-to-use publisher'
    imageLink: 'https://drawtify.com/free-flyer-maker/'

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @brucesong08 thank you for your app! Since its a closed source app, can you add a proof you use Electron in your app? It can be a screenshot of devtools opened 👍

**Comment by brucesong08** [comment]
Thanks for your quick reply. 
Here is the screenshot with devtools. 
https://drawtify.com/wp-content/uploads/2020/11/drawtify_design_screenshot_devtools.png

**Comment by Toinane** [comment]
I can't access to your screenshot :/
image

**Comment by brucesong08** [comment]
I uploaded it to Google driver.
Please try this link: 
https://drawtify.com/wp-content/uploads/2020/11/drawtify_design_screenshot_devtools.png

**Comment by Toinane** [comment]
Thank you @brucesong08 ! Its now okey for me! Can you just force update your last commit name to add "feat:" in name? or just add a new commit that have "feat: ...." in its name?

**Pull request merged**
