### PR TITLE
feat: Add FLB Music

### PR DESCRIPTION
**Pull request by Patrick-web**
### Checklist

- [x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [x] My application is open-source and has been created for at least 20 days
- [ ] My application is closed-source and here is a proof it uses Electron:

### Description
Offline first Music Player and Downloader 
Website is at https://flb.netlify.app/
app albums tab screenshot

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @Patrick-web thank you for your application! It looks good to me but I can't reach your website, can you fix that before I can merge? Thank you 👍

**Comment by Patrick-web** [comment]
Ok. The domain seems to be down. Let change the link

**Comment by Patrick-web** [comment]
I've changed the website link to a working one

**Comment by Toinane** [comment]
Thanks! But I don't see the changes

**Comment by Patrick-web** [comment]
I've changed the link in the pr to this  👉 https://flb.netlify.app/ is the change not visible on your side

**Comment by Toinane** [comment]
Okay, but yeah I don't see any new commit or changes, have you push your change here?

**Comment by Patrick-web** [comment]
Sorry. Gimme a sec.

**Comment by Toinane** [comment]
Thanks! @Patrick-web we have a new issue, your logo is a way too big, it need to be at leasr 1024x1024px

**Comment by Patrick-web** [comment]
Ok. Let fix that

**Comment by Patrick-web** [comment]
Sorry it took long.  Is everything ok now

**Pull request merged**
