### PR TITLE
feat: Add Multiplayer Game Heads or Tails

### PR DESCRIPTION
**Pull request by technologiespro**
Multiplayer Game: **Heads or Tails**

Web: https://dexgames.net/detail/heads-tails
Community: https://community.smartholdem.io/topic/662/dexgame-heads-or-tails
Creator: https://smartholdem.io

And now, the most popular game of “Heads or tails” is on the blockchain.
The information about every side of the coin is encrypted and saved in the blockchain. 
The game is played strictly between the players.

3_HOT98_26_10_2019

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @technologiespro ! Thank you for you game! Its look cool 👍 
I see your Electron application is a closed source. Can you provide a screenshot or video that show your app is built with Electron? (package.json, developper tools, ..)
Thank you!

**Comment by technologiespro** [comment]
[heads-or-tails.zip](https://github.com/electron/apps/files/4956843/heads-or-tails.zip)

The source code is based on electron + vue
the zip-archive contains all the main source code, at the moment it is closed but in the future it will be available for everyone

Thank you!

image

**Comment by Toinane** [comment]
Hey @technologiespro thank you for your reply 👍 
Its now all good!

**Comment by Toinane** [comment]
hey @technologiespro, can you delete your [electron-apps repository](https://github.com/technologiespro/electron-apps), I can't say why but I receive an email for each failed build of this repo 1 email each day actually 😅

**Comment by technologiespro** [comment]
yes ok deleted, thx

**Pull request merged**
