### PR TITLE
feat: Add Peacock Browser

### PR DESCRIPTION
**Pull request by spike-the-coder**
Hello, I'm submitting a web browser built in Electron.

image

### CODE REVIEW

**Comment by HashimotoYT** [comment]
@spike-the-coder Please allow editing this pull request from maintainers for easily merging this PR.

You can do this from PR sidebar:

Untitled

**Comment by spike-the-coder** [comment]
image
Sorry if I'm doing something wrong but I don't see that option in the sidebar of this PR?

**Comment by HashimotoYT** [comment]
Can you please try to move the fork from organization to your account it looks like similar to the situation what's we have in #1331.

**Comment by spike-the-coder** [comment]
Ah my bad. It's enabled now:
image

**Comment by spike-the-coder** [comment]
Thanks!

**Pull request merged**
