### PR TITLE
Add LBRY App

### PR DESCRIPTION
**Pull request by ykris45**
dgtwcuvx0au4aj2 
Website : https://lbry.io
im is a Trusted Member Of LBRY and as one of Community Contributor of LBRY App or LBRY Discord Server. 
You can find me at https://chat.lbry.io and find a chris45 username. that is me.. hehehe
i hope LBRY App can be added in here.. Thanks Alot

### CODE REVIEW

**Comment by codebytere** [comment]
@ykris if you could please address the CI failures, we can get this PR across the finish line!

**Comment by codebytere** [comment]
@ykris45 yaml files have a `.yml` ending not a `.yaml` ending :)

**Comment by ykris45** [comment]
@codebytere i think its correct, not sure i am, hehe

**Comment by codebytere** [comment]
@ykris45 i think i nailed down the issue: 
CI wants `apps/LBRY/LBRY.yml`
and you have `apps/LBRY/lbry.yml`.

Change `lbry.yml` => `LBRY.yml` and this should pass finally.

**Comment by ykris45** [comment]
@codebytere done renamed

**Comment by ykris45** [comment]
the name of Apps is LBRY App. not sure if travis ci build fail  any suggestion. ?

**Comment by ckerr** [comment]
You know what, I think I'd try using all-lowercase in the filenames, but keep the name as `LBRY` in the `name:` yml entry -- that should keep the bot and backend happy, but still appear as `LBRY` to human end users

**Comment by ykris45** [comment]
closed for now

**Pull request closed without merging**
