### PR TITLE
feat: Add Repic app.

### PR DESCRIPTION
**Pull request by margox**
### Checklist

- [x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [x] My application is closed-source and here is a proof it uses Electron:

repic e

### Description

Repic is a plug-in-based app for compressing images (or more kind of files in the future),  it's free and light-weight, visit [https://repic.app](https://repic.app) for more detail.

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @margox thank you for your application, It looks good but I can't access your website, it said the https is not secure. Can you fix that before I can merge? Thank you 👍

**Comment by margox** [comment]
@Toinane Sooooo sorry but the ssl certificate was expired at that very moment！😂 and I fixed it just now, so you can visit it now (https://repic.app).

**Comment by Toinane** [comment]
Ahah no worries @margox 😄 its now looks good to me! Can you update your branch from master so I can merge it?

**Comment by margox** [comment]
@Toinane updated, thank you so much!

**Comment by Toinane** [comment]
Thank you! It's done :)

**Pull request merged**
