### PR TITLE
feat: Add Biscuit

### PR DESCRIPTION
**Pull request by agata**
Website: https://eatbiscuit.com/

### CODE REVIEW

**Comment by 54D-R0807** [comment]
Where is the source code of Biscuit? Is it even open source? If so, what license is it?
Sorry if this is off-topic, but I could not find anything online. This seems to be the only place.

**Comment by agata** [comment]
@54D-R0807 Biscuit is not open source yet. I'm preparing about it.

**Comment by 54D-R0807** [comment]
Strange. There was an article about Biscuit on [Chip.de](https://www.chip.de/news/Biscuit-Browser-beendet-den-Tab-Wahnsinn_170292622.html) (the quality of this website has stagnated a lot over the past years) claiming that it was.

image

But that clears things up. Not wanting to pressure you, but what is holding you back from releasing the source? And what kind of license did you have in mind?

**Comment by agata** [comment]
Maybe Chip.de is misleading. I have to document some files(README with build information) and imrove some codes for easy to understand  by developers. I will use MIT for it.

**Pull request merged**
