### PR TITLE
Hive updated logo for website

### PR DESCRIPTION
**Pull request by michaelarollings**

### CODE REVIEW

**Comment by michaelarollings** [comment]
@Kilian Here is the PR with our updated logo. Please push this one through.

**Comment by Kilian** [comment]
Hi @michaelarollings thanks for this pull request. To get your new logo on the site, you need to _replace_ the following two images:

* [hive-icon-256.png](https://github.com/electron/apps/blob/52d9ef89976b5d2fe5850848aebfba2c3e8d9157/apps/hive/hive-icon-256.png)
* [hive-icon.png](https://github.com/electron/apps/blob/52d9ef89976b5d2fe5850848aebfba2c3e8d9157/apps/hive/hive-icon.png)


The file you included in this pull request won't be used, it needs to be named like the files above for it to work!

**Comment by HashimotoYT** [comment]
ping @michaelarollings

**Comment by HashimotoYT** [comment]
Closing due to inactivity. Please open new PR if to add your application.

**Pull request closed without merging**
