### PR TITLE
Add LBRY App

### PR DESCRIPTION
**Pull request by ykris45**
dgtwcuvx0au4aj2 
Website : https://lbry.io
im is a Trusted Member Of LBRY and as one of Community Contributor of LBRY App or LBRY Discord Server. 
You can find me at https://chat.lbry.io and find a chris45 username. that is me.. hehehe
i hope LBRY App can be added in here.. Thanks Alot

### CODE REVIEW

**Comment by ykris45** [comment]
@codebytere all check has been passed. thanks for your help

**Comment by ykris45** [comment]
@ckerr thanks you so much sir

**Comment by ykris45** [comment]
@ckerr its live now on https://electronjs.org/apps?q=d or not sir?

**Comment by ckerr** [comment]
It doesn't go live right away.

**Comment by ykris45** [comment]
owh. just asked to you. when it will live sir?

**Comment by ckerr** [comment]
Hmm, I'm not seeing it, either searching for `lbry` or `LBRY`, or even just looking in the [entertainment section](https://electronjs.org/apps?category=entertainment).

@zeke ^ any idea what might be wrong?

**Comment by ykris45** [comment]
@ckerr i think i must delete (-) to app name, Before i proposed lbry-desktop as app name, after remove (-) it should LBRY Desktop , that is my idea

**Pull request merged**
