### PR TITLE
feat: Add PaperArxiv

### PR DESCRIPTION
**Pull request by fuzihaofzh**
### Checklist

- [x ] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [x ] My application is open-source and has been created for at least 20 days
- [ ] My application is closed-source and here is a proof it uses Electron:

### Description

https://github.com/fuzihaofzh/PaperArxiv
PaperArxiv is a new paper management tool that helps to organize your mind. It focuses on taking notes, organizing, and archiving your files. Different from existing paper management tools that focus on reference management. PaperArxiv emphasizes on notes organizing as we believe a short note can bring more information to grasp the general idea.

### CODE REVIEW

**Comment by JaydenDev** [comment]
Just discovered this, but you have to add "feat:" at the start of the title for some reason.

**Comment by fuzihaofzh** [comment]
Thanks @JaydenDev . I have changed the title

**Comment by JaydenDev** [comment]
> Thanks @JaydenDev . I have changed the title

now all the checks have passed!

**Comment by JaydenDev** [comment]
@fuzihaofzh try updating your repository.

**Comment by JaydenDev** [comment]
I mean the repo you made your PR with.

**Pull request merged**
