### PR TITLE
feat: 'Add Tzared' 

### PR DESCRIPTION
**Pull request by donov55**

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @donov55 Thank you for your PR. I don't see where I can download an application on your website.
Also, its looks like this app is closed source. As per the [submission guidelines](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines), could you provide some evidence that this is an Electron app? [Previous PRs](https://github.com/electron/apps/pulls?utf8=%E2%9C%93&q=is%3Apr+evidence) are a good source for what other apps have used as evidence. Thanks!

**Comment by donov55** [comment]
> Hey @donov55 Thank you for your PR. I don't see where I can download an application on your website.
> Also, its looks like this app is closed source. As per the [submission guidelines](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines), could you provide some evidence that this is an Electron app? [Previous PRs](https://github.com/electron/apps/pulls?utf8=%E2%9C%93&q=is%3Apr+evidence) are a good source for what other apps have used as evidence. Thanks!

Hi! thanks for your response, here is the download link https://tza.red/#TzaredDesk

Evidence that is an electron app:
Anotación 2020-08-03 141443

**Comment by Toinane** [comment]
Hey @donov55 Thank you for your quick response! It looks good to me 👍 
In other way, I see you don't have french language for your game, I can propose you to help for this language if needed!

**Comment by donov55** [comment]
Thank you! I must add french translations but isn't a priority right now because there are almost no French players.
Regards!

**Pull request merged**
