### PR TITLE
feat: Add RBXUtil

### PR DESCRIPTION
**Pull request by JuiciiYT**
**RBXUtil** is an app which gets the user information of Roblox users, games and the catalog. The website can be found at [https://robloxutil.glitch.me](https://robloxutil.glitch.me). Here is a screenshot of it in use:
App Screenshot Here is our app logo:
App Logo

### CODE REVIEW

**Comment by D1WK** [comment]
Hehe nice

**Comment by JuiciiYT** [comment]
> Hehe nice

Thanks!

**Review by ckerr — COMMENTED** [review]
Hey, just for clarification -- is this app endorsed by Roblox Corp?

If not, you may want to consider modifying the app's name due to possible trademark issues. The [electron/apps contribution doc](https://github.com/electron/apps/blob/master/contributing.md#company-logos-and-names) has some information about this:

> Please do not directly use another company's name or product without permission. It's generally better to refer to it in a dependent clause; for example, after "compatible with", "on", or "for."
>
> For example, while we would not accept a third-party app named "GitHub Notifications", we would consider "Yourname Notifications for GitHub".
>
> While some existing apps in the collection predate this rule and have been grandfathered in, we will not accept any apps that do not follow this rule going forward.

**Comment by JuiciiYT** [comment]
No, its not but we have to have that name because that’s what it does so its easy for people to understand. Although we did ask Roblox but they didn’t reply.

**Comment by JuiciiYT** [comment]
okay ill try

**Comment by Toinane** [comment]
Hey @JuiciiYT Thanks for the update, but you need to update the folder name and your image's name too. Sorry for the late response

**Comment by Toinane** [comment]
Hey @JuiciiYT any news on your PR?

**Comment by Toinane** [comment]
As we don't have any news, I close this PR. Feel free to reopen it or make a new one

**Pull request closed without merging**
