### PR TITLE
feat: Add Q-player app

### PR DESCRIPTION
**Pull request by Toooorch**
Hey,

Here is the submission PR for the Q-player application.
This app allows users to listen to the Q-dance Radio station in the most convenient way.

screen2

image

It is used by some users already with good feedback
https://www.reddit.com/r/hardstyle/comments/bd7cdd/qplayer_qdance_radio_desktop_app/

The proof
image

Q-dance provided the permission to use the name Q-player.

Website: http://www.q-player.com
Downloads: https://github.com/Toooorch/q-player/releases

### CODE REVIEW

**Comment by Toooorch** [comment]
@Hongarc Thanks for suggestion suggestion. Changed that!

**Comment by Toooorch** [comment]
Hey @Hongarc,
everything ok? Ready to merge? 👀😀

**Comment by Hongarc** [comment]
I am a contributor, not a collaborator, I don't have permission to merge.

**Comment by Toooorch** [comment]
@Hongarc ok thanks 😊

**Comment by Toooorch** [comment]
Hey @ckerr Thanks for your review!

I have direct connection to Q-dance and they provided the permission to use the name Q-player so it can be used as-is. Added that to PR comment, is it enough?

**Comment by ckerr** [comment]
@Toooorch thanks for the confirmation :+1:

**Pull request merged**
