### PR TITLE
feat: VuPC

### PR DESCRIPTION
**Pull request by machester4**
This application is similar to [ScreenCat](https://github.com/electron/apps/tree/master/apps/screencat) which is no longer supported.
Maybe we could replace her from the list.

Thanks

### CODE REVIEW

**Comment by machester4** [comment]
@Toinane How are you? could you check this PR?

**Comment by Toinane** [comment]
Hey @machester4 thank you for your application! About it, I can't accept it for now because your repository should be 20 days old and at last a release download on it.

**Comment by machester4** [comment]
@Toinane Thank you for your answer, no problem, we will speak again in 20 days.
Thank you

**Comment by machester4** [comment]
@Toinane Hello, can we accept these changes?

**Comment by Toinane** [comment]
Sorry for the delay, its now okay to me!

**Pull request merged**
