### PR TITLE
feat: FNew-Desktop

### PR DESCRIPTION
**Pull request by Marnix0810**
screenshot
This is the [FNew Desktop](https://marnix0810.github.io/FNew/desktop-apps/) Electron app, you can download the Windows version [here](https://github.com/Marnix0810/FNew-Desktop-Windows/releases/latest)

### CODE REVIEW

**Comment by Marnix0810** [comment]
@HashimotoYT I build it with Nativefier which uses Electron and is open source, but I don't know how to prove it's build by Nativefier. Are Electron apps build using Nativefier permitted on Electron/Apps?

**Comment by Marnix0810** [comment]
By the way, the full output of Nativefier can be found at [https://github.com/Marnix0810/FNew-Desktop-Windows/tree/master/Nativefier-output/FNew%20Desktop-win32-ia32](https://github.com/Marnix0810/FNew-Desktop-Windows/tree/master/Nativefier-output/FNew%20Desktop-win32-ia32).

**Comment by Sanjit1** [comment]
You need to fix the CI error, to make sure that you are actually using electron. I think I found your [repository](https://github.com/Marnix0810/FNew), but I could not find anything about electron anywhere, inside the repo

```
 1) human-submitted app data
       fnew-desktop
         fnew-desktop.yml
           has a valid repository URL (or no repository):

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true
      
      at Context.it (test/human-data.js:112:63)

```

**Comment by Marnix0810** [comment]
I know. The repo for FNew itself is there but the repo containing the files of the actual electron app is elsewhere, I changed it in the yml file. It's at https://github.com/Marnix0810/FNew-Desktop-Windows.

**Comment by Sanjit1** [comment]
ping @HashimotoYT

**Comment by Sanjit1** [comment]
ping @ckerr

**Pull request merged**
