### PR TITLE
feat: Add Aether app

### PR DESCRIPTION
**Pull request by benhylau**
### Checklist

- [x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [x] My application is open-source and has been created for at least 20 days
- [ ] My application is closed-source and here is a proof it uses Electron:

### Description

Aether is an app for peer-to-peer ephemeral public communities.

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @benhylau thank you for your application! Can you rebase your branch from master or allow me to update it? Thank you 👍

**Comment by benhylau** [comment]
Merged. Is this ok? Thanks!

**Comment by Toinane** [comment]
hmm it need to be rebase again, or just let me the right to do it on checking the option from your PR 👍

**Comment by benhylau** [comment]
I cannot figure out how to allow you to update this PR, but I added you as a write-access contributor to the repo. Thanks.

**Comment by Toinane** [comment]
thanks @benhylau its now okay 👍

**Pull request merged**
