### PR TITLE
feat: Adding C'YaPass app for distribution.

### PR DESCRIPTION
**Pull request by raddevus**

### CODE REVIEW

**Comment by raddevus** [comment]
This was very confusing for a first-time pull requester.  I thought I got it and then the "semantic pull request" is in failure and I'm not sure what to do about that.

**Comment by gubareve** [comment]
@raddevus You need to add a Semantic prefix to your title ([here's a list of prefixes](https://github.com/commitizen/conventional-commit-types/blob/master/index.json)). For example you can change your title to `Fix: Adding C'YaPass app for distribution.`.

**Comment by Toinane** [comment]
Hey @raddevus thank you for your application ! Its looks good to me 👍

**Comment by raddevus** [comment]
@Toinane Thanks for your nice comment and your help getting it merged.

**Pull request merged**
