### PR TITLE
fix: disable broken app and add safeguards

### LINKED ISSUE #1856: CI is broken
https://github.com/electron/apps/runs/3317386998?check_suite_focus=true

### PR DESCRIPTION
**Pull request by erickzhao**
Fixes #1856

I found out that the SnailFM app was the culprit here due to an error processing the PNG file. I've disabled it and prevented all disabled apps from being processed in the build scripts.

cc @snaildos

### CODE REVIEW

**Comment by snaildos** [comment]
Huh.? What needs to be done here?

**Comment by malept** [comment]
> Huh.? What needs to be done here?

@snaildos seems like CI indicates that the icon you provided isn't actually a PNG.

**Comment by snaildos** [comment]
> > Huh.? What needs to be done here?
> 
> @snaildos seems like CI indicates that the icon you provided isn't actually a PNG.

My God. Sorry. That's my bad. Will work on a instant fix for this.

**Comment by malept** [comment]
Perhaps in a separate PR, a PR check should be added to make sure that any new icons are actually valid PNGs?

**Comment by snaildos** [comment]
SnailFM should be resolved on this PR, #1860

**Review by codebytere — APPROVED** [review]

**Pull request merged**
