### PR TITLE
feat: My folder online (share local folder easily)

### PR DESCRIPTION
**Pull request by idoio**
# Share your local folder easily
Simple app, that helps you share your local folder for view only (with downloads and zips).

## Features!

  - You can download as zip
  - Have preview for
    - Images: png, jpeg, gif, bmp, including 360-degree images
    - pdf
    - csv
    - xslx
    - docx
    - Video: mp4, webm
    - Audio: mp3
  - Fast, mulitypart download

### Easy to use

All you need to do is to input a folder path and start the server.
Then you get a fast link that you can share.

[Try it now][1]

[1]: https://my-folder-online.vercel.app/

### CODE REVIEW

**Comment by I-dodo** [comment]
Hey @ckerr, need your help.

I am trying to add my app to electron-js apps.
I'm a little confused, what did I do wrong? (The errors do not make sense to me)

I used this guild -> https://github.com/electron/apps/blob/master/contributing.md.
I really appreciate any help you can provide :)

**Comment by Toinane** [comment]
hey @I-dodo Any news about your PR?

**Comment by I-dodo** [comment]
> hey @I-dodo Any news about your PR?

Thanks for your help, I saw what happened wrong. :)

I will try to fix that when I have more free time. Right now I am really busy with school tests and stuff...

I will do it next week, (I don't want that issue remain open for no reason 😉)

**Comment by Toinane** [comment]
> > hey @I-dodo Any news about your PR?
> 
> Thanks for your help, I saw what happened wrong. :)
> 
> I will try to fix that when I have more free time. Right now I am really busy with school tests and stuff...
> 
> I will do it next week, (I don't want that issue remain open for no reason 😉)

No worries, it's okay 👍 Hope your tests will be fine, good luck!

**Pull request closed without merging**
