### PR TITLE
Added appget package IDs

### PR DESCRIPTION
**Pull request by kayone**
👋 
This builds on top of https://github.com/electron/apps/pull/337

I wrote a script that adds [AppGet ](https://appget.net) package IDs to matching electron apps. 

I also noticed that for some apps, AppGet had repository and license information that were missing form the electron app, so I synced those up to as well.

Please let me know if I've missed something!

### CODE REVIEW

**Comment by kayone** [comment]
That's great to hear! I wasn't sure about its prospect so I didn't put a ton of effort into it. I have a few more ideas on how to make the false negatives a bit more and sync more data between the repositories.

**Comment by zeke** [comment]
Wow thanks for taking the time to add this, @kayone. Did you do this all "by hand" or did you collect these names in some automated way?

I'm happy to merge this, but would also like to see it added to the documentation here: https://github.com/electron/apps/blob/master/contributing.md#yml-file-rules

**Comment by zeke** [comment]
@kayone if you'd like to help get this information on the website, this PR adding homebrew support could be used as a rough guide: https://github.com/electron/electronjs.org/pull/832

**Comment by kayone** [comment]
@zeke I'm a lazy programmer, so I spent a few months writing a full blown crawler/analyzer bot that scans a bunch of different sources (including this repo 😄 ) and creates automatic pull requests to https://github.com/appget/appget.packages/

Once this gets merged, If you guys don't mind I can do weekly PR requests to keep this repo in sync with new package added to AppGet

I've already added AppGet to https://github.com/electron/apps/pull/676/files#diff-cc4aac3e9be04e0413c9520f223b493c is that what you mean or am I missing something else?

Also, thanks for pointing me to https://github.com/electron/electronjs.org/pull/832, that was my next question I tried looking for the code in this repo but didn't find it, figured it might be somewhere else.

I'll try and get a PR on the electronjs repo tomorrow.

**Comment by zeke** [comment]
Hey thanks for weighing in, @MarshallOfSound. I wasn't paying close attention and was thinking `appget` meant `apt-get`... 🙈

Now that I've been edified, I tend to agree that appget may be too young a project for us to wholeheartedly endorse on the Electron website.

**Comment by kayone** [comment]
Even though I would love to have this added I completely understand your point of view. If you guys are ok with it, I'll update the PR to only include the updated license, repo information; at least that way I wouldn't have had waisted your time for nothing 😄 

Just to clear the _britle_ aspect of the manifests, AppGet has a github specific bot that checks for new releases hourly and submits a pull-request (once I'm a bit more sure of the accuracy and a few more checks are in place they will be automatically merged) It's not perfect but IMHO it's far ahead of what chocolatey does.

Hopefully in a couple of months when AppGet has more experiance/users behind it I'll 👋 you guys again.

Thanks for taking the time 😄

**Comment by zeke** [comment]
> I'll update the PR to only include the updated license, repo information

Sounds good. Thanks for understanding.

> Hopefully in a couple of months when AppGet has more experiance/users behind it

Definitely open to that 👍

**Comment by ckerr** [comment]
@MarshallOfSound I agree with your concerns, but I don't think it's a dealbreaker to have community-based PRs that do the software updates -- that's not so different from PPAs. And if you want to improve the metadata for your own app, you can [file a PR](https://github.com/appget/appget.packages/pulls) to do that.

Moreover, I don't think we should be taking sides on package manager A vs package manager B. I'm mostly in favor of this PR, and if there was a similar PR for (say) Chocolatey I'd be in favor of that as well.

To step back a moment though -- Do  we have _any_ cases where an app has different names on Snap and on Homebrew? Wouldn't "packageName" be enough instead of having a different entry for each package manager?

**Comment by zeke** [comment]
> Do we have any cases where an app has different names on Snap and on Homebrew?

I don't know of any specific instances, but would not say it's safe to assume they'd be the same.

**Comment by kayone** [comment]
> Would "packageName" be enough instead of having a different entry for each package manager?

I think that would be a really big assumption. the other issue would be having just a generic `package_id` would be too vague and also it would imply a package with ID is available on all different package managers. 

just looking at _this_ PR, I only had to go down to Bs to find the first example

```
 name: BunqDesktop
 description: 'A desktop implementation for the bunq API.'
 website: 'https://bunqdesktop.com'
 license: 'MIT License'
 appgetName: bunqdesktop
 repository: 'https://github.com/BunqCommunity/BunqDesktop'
 category: 'Finance'
 homebrewCaskName: bunq
```

**Comment by ckerr** [comment]
I'm closing this PR as part of a bulk-closing of stale PRs that appear to no longer be applicable.

If anyone thinks this PR is still valid and thinks it should be reconsidered, please rebase / update the patch to `master` and open a new PR. Thank you!

**Pull request closed without merging**
