### PR TITLE
Lucasnkl626 patch 1

### PR DESCRIPTION
**Pull request by lucasnkl626**
### Checklist

- [x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [x] My application is open-source and has been created for at least 20 days
- [ ] My application is closed-source and here is a proof it uses Electron:

### CODE REVIEW

**Review by lucasnkl626 — COMMENTED** [review]
#1931

**Review by lucasnkl626 — COMMENTED** [review]
#1931 
Duplicate of #1931

**Comment by lucasnkl626** [comment]
`semastic pull
Duplicate of #`

**Comment by JaydenDev** [comment]
Your PR is a "fix" you should add the "fix: " prefix to your PR name to pass the Semantic PR check.

**Pull request closed without merging**
