### PR TITLE
docs: update Commandeer app screenshots

### PR DESCRIPTION
**Pull request by fsproru**
Hi, updating some obsolete screenshots and the description for the Commandeer app.

Here are the screenshots to make the review easier:

screenshots:
  - imageUrl: 'https://images.commandeer.be/_screenshots/dynamo-dashboard.png'
    caption: 'View Your Data'
  - imageUrl: 'https://images.commandeer.be/_screenshots/ansible-runner.png'
    caption: 'Build Your IAC'
  - imageUrl: 'https://images.commandeer.be/_screenshots/system-diagrams.png'
    caption: 'Test Your Plumbing'

### CODE REVIEW

**Comment by fsproru** [comment]
@vhashimotoo, @Sanjit1, would you mind taking a look at this PR when you get a chance? Would love to get it merged so Commandeer screenshots show up because the links got broken during a migration.

**Comment by vhashimotoo** [comment]
@fsproru First of all, need to notice that I'm not more maintain the Electron projects, so please don't ping me or any other project member if PR doesn't get a review, all reviews in this repo do by project maintainers. Your Pull Request to be reviewed someday.

**Comment by fsproru** [comment]
Hey @vhashimotoo, apologies, didn't realize that you're no longer a maintainer. Just wanted to follow up here in case this PR felt through the cracks :-). Understandable that the maintainers will review it when available. Have a good one.

**Comment by Toinane** [comment]
Hey @fsproru I'm sorry for the late response, It's all good to me!

**Pull request merged**
