### PR TITLE
feat: updated bibisco.yml

### PR DESCRIPTION
**Pull request by andreafeccomandi**
Added youtube URL, removed repository because you can download the latest release of the app only from bibisco website.

### CODE REVIEW

**Comment by Toinane** [comment]
Hm, I hope so, I don't know how its work for this information, I'll take a look into the code, I suppose its just a matter of time with the next website update but i'm not sure about that

**Comment by Toinane** [comment]
Its now good on the website! @andreafeccomandi

**Comment by andreafeccomandi** [comment]
Thank you @Toinane! 
I have restored the repository reference in bibisco.yml. 
In this pull request version of bibisco.yml there is therefore only the indication of the introductory video on youtube.

**Comment by Toinane** [comment]
Cool! Thank you 👍

**Pull request merged**
