### PR TITLE
feat: Add 'Desktop Recorder' app

### PR DESCRIPTION
**Pull request by jgcoded**
Hello, I would like to submit my app.

Short Description:
_Record your desktop with this free, simple app. Start a YouTube channel, record a product demo, or create a how-to video for friends and family!_

Screenshot:
Screenshot

Windows store link: https://www.microsoft.com/en-us/p/desktop-recorder/9nqb7l1kx84k

Full Description:
_Record your desktop with this free, simple app. Start a YouTube channel, record a product demo, or create a how-to video for friends and family!_

_Just press the big red button and recording will start. When you're done recording, press your designated hotkey and your video will be saved to your Videos folder. If something goes wrong while recording, the app will try and save what you had recorded so far._

_Use this app as an easy tool to record your screen, and then use other apps to edit, zoom, and add music to your video._

Evidence of being created with Electron:
image

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @jgcoded Thank you for your app submission!
Can we know which version of Electron do you use in your application?

**Comment by jgcoded** [comment]
Hi @Toinane, I recently moved to Electron 9.0:

image

**Comment by Toinane** [comment]
Hey @jgcoded thank you for your response! Its all good for us. 👍

**Comment by jgcoded** [comment]
Thanks!

**Pull request merged**
