### PR TITLE
feat: Add Wanna-Class

### PR DESCRIPTION
**Pull request by MissterHao**
### Checklist

- [x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [x] My application is open-source and has been created for at least 20 days
- [ ] My application is closed-source and here is a proof it uses Electron:

### Description

Campus desktop software for YuanZe University students to select wanted course.

Website: https://github.com/MissterHao/WannaClass/

Repository: https://github.com/MissterHao/WannaClass/

Screenshot: 
Index Screen
Course Selection Screen
Login Screen
Loading Screen

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @MissterHao thank you for your app! Looks good to me 👍

**Comment by MissterHao** [comment]
@Toinane Thank you very much!
I can search my app on [Electron.js apps page](https://www.electronjs.org/apps) from now on, right? 😃

**Comment by Toinane** [comment]
It need from 2hours to a day to have your app in Electronjs.org page 👍

**Comment by MissterHao** [comment]
Got it! Thanks for answering me!

**Pull request merged**
