### PR TITLE
feat: add app horen

### PR DESCRIPTION
**Pull request by kevinjobs**
### Checklist

- [x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [x] My application is open-source and has been created for at least 20 days
- [ ] My application is closed-source and here is a proof it uses Electron:

### Description

yet another player music.

https://github.com/horenjs/Horen

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @kevinjobs thank you for your application! Can you allow maintainers to edit your PR? thank you!

**Comment by kevinjobs** [comment]
> Hey @kevinjobs thank you for your application! Can you allow maintainers to edit your PR? thank you!

How can I allow maintainers to edit my PR?
What should I do...

**Comment by Toinane** [comment]
You can do it on the right panel like here:
image

**Comment by kevinjobs** [comment]
> You can do it on the right panel like here: image

I dont know why, but there is no option on the right panel like that.

**Comment by Toinane** [comment]
Hm okay strange! I'll add your app from my side with another pr so!

**Comment by kevinjobs** [comment]
> Hm okay strange! I'll add your app from my side with another pr so!

thank you!

**Pull request closed without merging**
