### PR TITLE
feat: Add SQL Client

### PR DESCRIPTION
**Pull request by rnowak8**
### Checklist

- [x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [ ] My application is open-source and has been created for at least 20 days
- [x] My application is closed-source and here is a proof it uses Electron:

image

### Description

SQL Client app is a MySQL (will support more databases in the future) client with GUI, based on ReactJS. Currently available for Windows, but will be also available for Linux and macOS.

Website: https://sql-client.com/

Screenshots:
image
image
image
image

### CODE REVIEW

**Comment by rnowak8** [comment]
@BlackHole1 Do you need anything more or could you merge?

**Review by BlackHole1 — APPROVED** [review]
LGTM

**Comment by BlackHole1** [comment]
Since the CI is not running, I need to close this PR and reopen it. in order to get the CI running again.

**Comment by BlackHole1** [comment]
Thanks for the app!

**Pull request merged**
