### PR TITLE
feat: Add EnderFramework

### PR DESCRIPTION
**Pull request by EnderAdel**
Hello there! 
Here is the description of my app:
<h1>EnderFramework</h1>
<h3>EnderFramework is a framework than can make it easier to build apps</h3>
<hr>
<h3>You can find more about this framework in <a href="https://enderadel.net/EnderFramework">here</a>!</h3>
<br>
<h5>This is a built-in app, it's called EnderStudio.</h5>

<h5>This is a built-in app, it's called EnderInstaller.</h5>

<h5>You can use it to install EnderApps! (.EPK files that don't contain any of the node modules or Electron files)</h5>

<h5>This is an example of an app built using custom elements and EnderAPI in EnderFramework:</h5>

### CODE REVIEW

**Comment by EnderAdel** [comment]
When will this get added to the repository?

**Comment by EnderAdel** [comment]
Is there anything that I need to do before you can approve of my app?

**Comment by Toinane** [comment]
Hey @EnderAdel thank you for your framework, yes, we need to wait at last 20 day old for your repository. 👍 
It will be merged when this requirement will be ok, and before that you can add a release on your repository to make easier to download your framework.

**Comment by EnderAdel** [comment]
I can't add a release @Toinane . The framework isn't ready for release yet.

**Comment by EnderAdel** [comment]
The repository is old enough to be added now, right?

**Comment by EnderAdel** [comment]
Yeah, I'm pretty sure that it's ~21 days old.

**Comment by EnderAdel** [comment]
It was created on September 12th, 2020. The date now is October 1st, 2020. So it's 20 days old.

**Comment by EnderAdel** [comment]
This application isn't incomplete anymore. And the repository is old enough. When will you approve of it?

**Review by vhashimotoo — CHANGES_REQUESTED** [review]
Your application doesn't contain any ability to download ready to use the platform (macOS, Linux, Windows) binary. When this requirement will be done, we can continue the review.

**Comment by EnderAdel** [comment]
And what is this `binary`?

**Comment by EnderAdel** [comment]
@vhashimotoo, can you at least send some links that can help me understand what I have to do?

**Comment by vhashimotoo** [comment]
Under this, I'm mean how to consumer get your product? The official website doesn't contain any links to ready to use binaries:

image

If your website doesn't provide direct downloading of the app, this should be in your GitHub repository, but they don't contain any releases with ready to use binaries:

image

Since your application is unable to download, currently we unable to approve him.

**Comment by EnderAdel** [comment]
But it's not really ready for release...

**Comment by EnderAdel** [comment]
Ok, I've updated it now. https://enderadel.net/EnderFramework/download/

**Comment by EnderAdel** [comment]
@vhashimotoo, I'm ready for a new review.

**Comment by EnderAdel** [comment]
Can anyone review this application?

**Comment by Toinane** [comment]
Hey @EnderAdel thank you for the update for the download link, its now okay! 👍

**Pull request merged**
