### PR TITLE
feat: add 'hexo-blog-client' app

### PR DESCRIPTION
**Pull request by Xonlystar**

### CODE REVIEW

**Comment by Xonlystar** [comment]
I have contacted Hexo, and obtained the permission. Here is my [issue](https://github.com/hexojs/hexo/issues/3554)

image

**Comment by ckerr** [comment]
> I have contacted Hexo, and obtained the permission. Here is my [issue](https://github.com/hexojs/hexo/issues/3554)

Thank you for asking Hexo!

Could you please include a screenshot of them granting permission?

**Comment by tcrowe** [comment]
I'm a maintainer on hexo. This is the first we've heard of @Xonlystar or the GUI client project so please give us some patience while we look into it.

Issues (1) https://github.com/hexojs/hexo/issues?utf8=✓&q=involves%3Axonlystar
PRs (0) https://github.com/hexojs/hexo/pulls?utf8=✓&q=involves%3Axonlystar

There is a policy to name modules like:
+ `hexo-renderer-ejs`
+ `hexo-tag-youtube`
+ `hexo-*`

`hexo-blog-client` works with our guidelines.

Lets see if this works ➡️ @hexojs/founder @hexojs/core would you like to chime in? Would you like `hexo-blog-client` by Xonlystar up on the Electron app list?

**Comment by tcrowe** [comment]
(I don't think the team name worked.)

Dear @tommy351, @NoahDragon, @YoshinoriN, @segayuu

Would you like to chime in? Would you like [hexo-blog-client](https://github.com/Xonlystar/hexo-blog-client) by [Xonlystar](https://github.com/Xonlystar) up on the Electron app list?

**Comment by YoshinoriN** [comment]
IMHO it's okay to add Electron app list. There are two reasons.

1. As you know `hexo-*` naming application is [already exists](https://electronjs.org/apps/hexo-client).
2. Maybe Hexo team will not release an Electron application officially. (If we will create & release official an Electron application, I disagree with this issue)

Btw, I'm the newest maintainer in Hexo. I want to hear other active maintainer's opinion.

**Comment by ckerr** [comment]
OK. Since one maintainer replied in the affirmative and 10 days have passed without dissent from the other maintainers, I'm going to merge this.

**Pull request merged**
