### PR TITLE
Add Apps: Tern

### PR DESCRIPTION
**Pull request by 1c7**
Hi, I built a Electron.js app http://tern.1c7.me/
and want to add it into app list, Thank you

### CODE REVIEW

**Comment by 1c7** [comment]
## Proof
Here is a Youtube video to proof "Tern" is a Electron.js App
https://www.youtube.com/watch?v=xPcBMVZPUWY

Thank you

**Comment by Toinane** [comment]
Hey there! Thank you for your application, seem to be good about the proof video.
About the category, your application would be better in Utilities or Productivity category than Education

**Comment by 1c7** [comment]
@Toinane Thank you, I would change that `category` tomorrow (it's very late now for me)

**Comment by Toinane** [comment]
No problem ! 👍

**Comment by 1c7** [comment]
Done. @Toinane please review this if possible, Thank you!

**Comment by Toinane** [comment]
Hey @1c7 thank you for the update ! Its all good to us! Thank you for your application 👍

**Pull request merged**
