### PR TITLE
feat: added RocketCleaner app

### PR DESCRIPTION
**Pull request by miladdavoodi**
https://github.com/miladdavoodi/RocketCleaner

### CODE REVIEW

**Comment by Sanjit1** [comment]
This is not what I asked you to do. You were supposed to make changes in your own fork of apps. You were not supposed to go to my fork and create a pull request. Close this Pull request and open another one from [here](https://ww.github.com/miladdavoodi/apps) after you have done the changes. If you are still confused then tell me in the issue, and I will do the work for you and will add both of your apps to the electron website.

**Comment by miladdavoodi** [comment]
Yes please do
Thanks
Please only add RocketCleaner

> The Postson program is not complete and I am working on it

**Comment by Sanjit1** [comment]
Ok kool just close or delete this pull request

**Comment by Sanjit1** [comment]
Please delete this pull request so This I can open my own.

**Pull request closed without merging**
