### PR TITLE
feat: add Termy

### PR DESCRIPTION
**Pull request by martonlanga**
Website: https://termy.app
Repository: https://github.com/termyapp/Termy
Screenshot: https://termy.app/screenshot.jpg

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @martonlanga thank you for your application! Can you move your termy folder in the apps/ folder? Thank you! 👍

**Comment by martonlanga** [comment]
Sorry I missed that, pushed a fix @Toinane

**Comment by Toinane** [comment]
No worries! Thank you for the fix @martonlanga

**Comment by Toinane** [comment]
Ah, it seem your image is too bigger, it should be max 1024px*1024px

**Comment by martonlanga** [comment]
Could you try now?

**Comment by Toinane** [comment]
Its now good! Thanks!

**Pull request merged**
