### PR TITLE
feat: Add Strimio 

### PR DESCRIPTION
**Pull request by strimio**
### Checklist

- [ x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [ ] My application is open-source and has been created for at least 20 days
- [ X] My application is closed-source and here is a proof it uses Electron:
image

### Description

Strimio is a free cloud-based streaming service that provides you access to tens of thousands of live streams from all over the world.

https://dashboard.snapcraft.io/site_media/appmedia/2021/01/Strimio_banner_1920_1080_copy.png
https://www.strimio.com/images/hero.png
https://www.strimio.com/images/strimio-dark-home.jpg

https://strimio.com

### CODE REVIEW

**Comment by Toinane** [comment]
Hey there! Thank you for your application! Looks good to me 👍

**Comment by Toinane** [comment]
Ha, looks your color is not accessible, can you edit that @strimio ?

**Comment by strimio** [comment]
@Toinane removed the colors, for now, maybe I'll update later, thanks!

**Comment by Toinane** [comment]
Looks like you have some others errors

**Comment by meni-melio** [comment]
@Toinane sorry, fixed!

**Pull request merged**
