### PR TITLE
feat: add social browser app

### PR DESCRIPTION
**Pull request by absunstar**

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @absunstar thank you for your application! As required on guideline, we need a proof you use Electron. It can be a screenshot of devtools or the package.json!
And you need to update your SSL certificate, I can't access your website for now.

**Comment by Toinane** [comment]
Hey @absunstar any news about your application?
If I don't have any update here, I'll need to close this PR

**Comment by absunstar** [comment]
https://social-browser.com/
ssl ok

**Comment by absunstar** [comment]
this is package.json content

{
  "name": "social_browser",
  "productName": "Social Browser",
  "homepage": "https://social-browser.com",
  "version": "2020.09.20",
  "description": "Browsing Any Site with Multi Users And without Ads",
  "author": {
    "name": "Social Developer",
    "email": "social.browser.com@gmail.com"
  },
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/absunstar/social-browser.git"
  },
  "main": "social.js",
  "scripts": {
    "win": "electron-builder -w --x64 --ia32",
    "win32": "electron-builder -w --ia32",
    "win64": "electron-builder -w --x64",
    "ubuntu": "electron-builder -l --x64 --ia32",
    "mac": "electron-builder -m --x64",
    "postinstall": "electron-builder install-app-deps",
    "start": "gulp && electron .",
    "init": "gulp",
    "reload": "gulp && electron-rebuild",
    "pack": "electron-builder --dir",
    "dist": "electron-builder"
  },
  "build": {
    "appId": "com.social.browser",
    "productName": "Social Browser",
    "copyright": "Copyright © 2020",
    "target": "NSIS",
    "files": [
      "**/*",
      "!**/.vscode",
      "!**/.git",
      "!**/node_modules",
      "!**/social-data",
      "!**/test",
      "!**/downloads",
      "!**/uploads",
      "!**/build"
    ],
    "protocols": [
      {
        "name": "Social Browser Explorer File URL",
        "schemes": [
          "HTTP",
          "HTTPS"
        ],
        "role": "Viewer"
      }
    ],
    "directories": {
      "output": "../build"
    },
    "win": {
      "target": "NSIS",
      "icon": "browser_files/images/logo.ico",
      "fileAssociations": [
        {
          "ext": "html",
          "icon": "browser_files/images/html.ico"
        },
        {
          "ext": "pdf",
          "icon": "browser_files/images/pdf.ico"
        }
      ]
    },
    "nsis": {
      "artifactName": "${productName} Setup.${ext}",
      "uninstallDisplayName": "${productName}",
      "allowElevation": true,
      "oneClick": false,
      "perMachine": false,
      "createDesktopShortcut": "always",
      "createStartMenuShortcut": true,
      "menuCategory": true,
      "shortcutName": "Social Browser",
      "installerIcon": "browser_files/images/logo.ico",
      "allowToChangeInstallationDirectory": true
    },
    "squirrelWindows": {
      "msi": true
    },
    "mac": {
      "category": "public.app-category.entertainment",
      "icon": "browser_files/images/logo.icns",
      "target": [
        "zip",
        "dmg"
      ]
    },
    "linux": {
      "category": "Web",
      "icon": "browser_files/images/logo.png",
      "target": [
        "deb",
        "AppImage"
      ]
    },
    "snap": {
      "confinement": "classic",
      "useTemplateApp": "false"
    }
  },
  "dependencies": {
    "custom-electron-titlebar": "^3.2.4",
    "ibrowser": "^1.0.7",
    "isite": "^1.14.29",
    "jquery": "*"
  },
  "devDependencies": {
    "electron": "^10.1.5",
    "electron-builder": "^22.7.0",
    "gulp": "*"
  }
}

**Comment by absunstar** [comment]
i make app public on https://github.com/absunstar/social-browser

**Comment by absunstar** [comment]
hi @Toinane 
i wish to add my app to electron apps
thanx

**Comment by Toinane** [comment]
Thank you @absunstar its now okay for me 👍

**Comment by Toinane** [comment]
As I don't have any news from months, I'll close this pr for now, feel free to reopen it if needed

**Pull request closed without merging**
