### PR TITLE
feat: Added entry for "Google Assistant Unofficial Desktop Client"

### PR DESCRIPTION
**Pull request by Melvin-Abraham**
**Repository:** https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client

### CODE REVIEW

**Review by vhashimotoo — CHANGES_REQUESTED** [review]
As per https://github.com/electron/apps/blob/master/contributing.md#company-logos-and-names --

If `Google` has given you permission to use that name, please provide that information in the PR so that the app's name can be used as-is. Otherwise,

> Please do not directly use another company's name or product without permission. It's generally better to refer to it in a dependent clause; for example, after "compatible with", "on", or "for."
>
> For example, while we would not accept a third-party app named "GitHub Notifications", we would consider "Yourname Notifications for GitHub".

**Comment by Melvin-Abraham** [comment]
Would it work if I change the application name in the yml file to **"Unofficial Desktop Client for Google Assistant"**?

**Comment by ckerr** [comment]
> Would it work if I change the application name in the yml file to **"Unofficial Desktop Client for Google Assistant"**?

Yes, that would follow the guidelines. :+1:

**Comment by Melvin-Abraham** [comment]
@vhashimotoo Updated application name in YML file...

**Comment by Toinane** [comment]
Thank you for the name update! It looks good now 👍

**Pull request merged**
