### PR TITLE
feat: Add Jabra Direct app

### PR DESCRIPTION
**Pull request by frederiksen**

### CODE REVIEW

**Comment by frederiksen** [comment]
image

**Comment by Toinane** [comment]
Hey @frederiksen thank you for your application! It is possible to know the version Electron do you use?

**Comment by Toinane** [comment]
hey @frederiksen I didn't received any news from you, just a reminder here

**Comment by frederiksen** [comment]
Back from vacation. Current Jabra Direct version uses Electron version: 6.1.7

**Comment by Toinane** [comment]
Hey @frederiksen Thank you for your response 👍 
Hope you had good vacation!
About Electron version, you should use 6.1.12 if possible or in best case update to the latest version when possible.
Looks good to me now thank you!

**Comment by Toinane** [comment]
Can you update your branch on master that I can merge it? Thank you!

**Comment by frederiksen** [comment]
@Toinane - yes please merge.

**Comment by Toinane** [comment]
I can't before you rebased your branch on master, or can you allow edit this pull request for maintainers. You can do that in the pull request sidebar:
need edit rights

**Comment by frederiksen** [comment]
Thanks @Toinane - now the branch has been updated, and should be ready for merge.

**Comment by Toinane** [comment]
Thank you @frederiksen ! Its good now!

**Pull request merged**
