### PR TITLE
feat: Gautham

### PR DESCRIPTION
**Pull request by gauthamshekar**

### CODE REVIEW

**Review by ckerr — COMMENTED** [review]
Hey @gauthamshekar, thank you for your application! As required in guidelines, your repository must be 20 days old, so I can't merge for the moment.

**Comment by sgn2000** [comment]
> Hey @gauthamshekar, thank you for your application! As required in guidelines, your repository must be 20 days old, so I can't merge for the moment.

Ya thank you for the reply now what should i do to make my repository 20 days old please let me know because I'm new to these pull request and github.

**Comment by nbebaw** [comment]
You have just to wait until your repo is 20 days old.

**Comment by nbebaw** [comment]
> > Hey @gauthamshekar, thank you for your application! As required in guidelines, your repository must be 20 days old, so I can't merge for the moment.
> 
> Ya thank you for the reply now what should i do to make my repository 20 days old please let me know because I'm new to these pull request and github.

You have just to wait until your repo is 20 days old.

**Comment by gauthamshekar** [comment]
Now my repository is 20 days old please look into it

**Comment by Toinane** [comment]
Hey @gauthamshekar thanks for your application and sorry for the late response. Actually, I can't add your app, can you make some efforts to present your app on your repository? Like add a readme with somes screens, add a release to download your app. It would be cool and give more interest into your app

**Comment by Toinane** [comment]
Hey @gauthamshekar any news on your PR?

**Comment by Toinane** [comment]
As we don't have any news, I close this PR. Feel free to reopen it or make a new one.

**Pull request closed without merging**
