### PR TITLE
TrackingTime added

### PR DESCRIPTION
**Pull request by trackingtime**
Hi, here the public download link https://trackingtime.co/tray-desktop-app is built with Electron 4.2.0

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @EricTulle Thank you for your application!
Like you application is a closed source, can you provide a screenshot or video that show your app is built with Electron? (package.json, developper tools, ..)
Also, it would be great if you can update Electron version to latest, 4.2.0 is a pretty old version now and can be a security issue.

**Comment by trackingtime** [comment]
Hi @Toinane , thanks for the advice we will update it!
Here the screenshot you asked. 
Cheers!

Screen Shot 2020-07-10 at 9 56 34 AM

**Comment by Toinane** [comment]
Hey @trackingtime thank you! Its all good now!
Thanks for the application 👍

**Comment by trackingtime** [comment]
Thank you!

**Pull request merged**
