### PR TITLE
feat: Added TaskView app

### PR DESCRIPTION
**Pull request by Gimanh**
Add TaskView app

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @Gimanh we didn't received any news from you here, is this PR still relevant?
Thank you!

**Comment by Gimanh** [comment]
> Hey @Gimanh we didn't received any news from you here, is this PR still relevant?
> 
> Thank you!

Hi! Yes this PR is relevant! Sorry fo wait I had some problem with internet connection. I will give information today or tomorrow! Thanks!

**Comment by Gimanh** [comment]
> Hey @Gimanh we didn't received any news from you here, is this PR still relevant?
> Thank you!
Hi! Where is screenshot with console. Is this enough?
Screenshot 2020-07-27 at 22 34 56

**Comment by Gimanh** [comment]
> Hey @Gimanh Thank you for your update, its look good to me.
> Thank you for your application! 👍

Thanks for your work!

**Pull request merged**
