### PR TITLE
feat: Add Redily

### PR DESCRIPTION
**Pull request by stefanoarnone**

### CODE REVIEW

**Comment by stefanoarnone** [comment]
Hi Vlad,
here is evidence that it is an electron app:

redily-electron-screen

**Comment by stefanoarnone** [comment]
Waiting for approval

**Comment by stefanoarnone** [comment]
> Thanks for the app 💛

Thanks for Electron =)

**Comment by gustavo-vendramini-oktagon** [comment]
@stefanoarnone hi man, your app is great!!!
Whats happen, the Redily webpage is down =/

If you don't intent maintain so open the source for us =)

**Pull request merged**
