### PR TITLE
feat: Add Compress app.

### PR DESCRIPTION
**Pull request by fedegratti**
Website: https://compress.ohzi.io
image

### CODE REVIEW

**Comment by Toinane** [comment]
Hey there! Thanks for your application!
Looks like this app is closed source. As per the [submission guidelines](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines), could you provide some evidence that this is an Electron app? [Previous PRs](https://github.com/electron/apps/pulls?utf8=%E2%9C%93&q=is%3Apr+evidence) are a good source for what other apps have used as evidence. Thanks!

**Comment by fedegratti** [comment]
Hey @Toinane, thank you for the quick revision! 
Here's an evidence that this is an Electorn app: 
image

Let me know if you need anything else.

**Comment by Toinane** [comment]
Look good to me @fedegratti thank you!
Just a tips, you should remove your video folder from your release exe, you'll gain 84mo for your app. 👍

**Comment by fedegratti** [comment]
@Toinane awesome advice! I just did it, thank you!

**Pull request merged**
