### PR TITLE
feat: add quickredis

### PR DESCRIPTION
**Pull request by quick123official**

### CODE REVIEW

**Comment by quick123official** [comment]
> Hey @quick123official thank you for application, as it seem to be closed source, we need a proof that it use Electron. It can be a screenshot of devtools or package.json.
> 
> Also you need to make a bigger app icon, at least 256x256px and you can't start your app description with the name of your application and its maybe a little bit too long.
> 
> Thank you! 👍

Has been revised again, please review. Thanks!

**Comment by Toinane** [comment]
Ah, you don't have to add screenshots proof in your commit but in description or comments, its good for the proof, can you remove it from PR? We just need the yaml file and icon, also your icon is 250*250px, and not 256*256px, can you make it a little bigger?

Thank you for your effort! 👍

**Comment by quick123official** [comment]
> Ah, you don't have to add screenshots proof in your commit but in description or comments, its good for the proof, can you remove it from PR? We just need the yaml file and icon, also your icon is 250_250px, and not 256_256px, can you make it a little bigger?
> 
> Thank you for your effort! 👍

Hi, Toinane. package.json.jpg & screenshot.jpg had been delete.

**Comment by quick123official** [comment]
Hi, Toinane. Here is package.json.jpg & screenshot.jpg.
https://quick123.net/images/package.json.jpg
https://quick123.net/images/screenshot.jpg

**Comment by Toinane** [comment]
> Hi, Toinane. Here is package.json.jpg & screenshot.jpg.
> https://quick123.net/images/package.json.jpg
> https://quick123.net/images/screenshot.jpg

Perfect, its just need a bigger icon now!

**Comment by quick123official** [comment]
> > Hi, Toinane. Here is package.json.jpg & screenshot.jpg.
> > https://quick123.net/images/package.json.jpg
> > https://quick123.net/images/screenshot.jpg
> 
> Perfect, its just need a bigger icon now!


For a programmer, making an icon is a bit difficult. Can I continue to use the existing 255*255 px image? :)

**Comment by Toinane** [comment]
But your icon has the same time as before.. You need to make it bigger. I took the liberty of redoing it so that it could be in good standing. You can use it and it will be okay after that.

logo

**Comment by quick123official** [comment]
> But your icon has the same time as before.. You need to make it bigger. I took the liberty of redoing it so that it could be in good standing. You can use it and it will be okay after that.
> 
> logo

I have modified the icon. Thank you very much!

**Comment by Toinane** [comment]
Thank you! Its now okay for us! 😃

**Comment by quick123official** [comment]
That is great! Thank you！

**Pull request merged**
