### PR TITLE
Create Meta0XCoin

### PR DESCRIPTION
**Pull request by Aivolt1**
### Checklist

- [x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [x] My application is open-source and has been created for at least 20 days
- [x] My application is closed-source and here is a proof it uses Electron:

### CODE REVIEW

**Comment by KorbsStudio** [comment]
Yeah, rename this to "feat: add Meta0XCoin" and the Semantic Pull Request will find it valid.

**Review by Aivolt1 — COMMENTED** [review]
952A6252-FB5B-4A65-99A8-D504F1DF3664

**Comment by ThatOneCalculator** [comment]
My monkey jpeg now, sucker!

![])(https://user-images.githubusercontent.com/74842886/152873664-b85a3bf8-1156-4828-9e2b-f3a441ee39dc.jpeg)

**Comment by KorbsStudio** [comment]
Screw this I'm out

**Pull request closed without merging**
