### PR TITLE
feat: add zonote

### PR DESCRIPTION
**Pull request by zonetti**

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @zonetti thank you for your application!
Your repository need to be 20days old before i can merge it as required in the Submission Guidelines.

**Comment by zonetti** [comment]
I see. I'll wait then. Thank you.

**Comment by zonetti** [comment]
@Toinane Can it be merged now?

**Comment by zonetti** [comment]
@Toinane what do I need to do to show the README on the app's page (https://www.electronjs.org/apps/zonote)?

**Pull request merged**
