### PR TITLE
feat: Add DiscordRPCMaker

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
### Checklist

- [x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [x] My application is open-source and has been created for at least 20 days

### Description

It allows people to create custom rich presences for Discord. Unlike other apps, this has its own developer portal built in, has an actually good editor and supports the new Discord buttons.

### [Repo](https://github.com/thatonecalculator/discordrpcmaker)

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
@zeke :pleading_face:

**Comment by zeke** [comment]
Hello. I am no longer a maintainer of this project. I think @electron/wg-ecosystem is the right team to ping.

**Comment by Toinane** [comment]
I'll looking it soon, sorry i'm on vacations actually

**Comment by ThatOneCalculator** [comment]
> youtube_video_url is optional, but must be a fully-qualified URL if provided.

Reminder to myself to add this when i have the chance

**Review by erickzhao — APPROVED** [review]

**Review by erickzhao — CHANGES_REQUESTED** [review]
Looks like the file format requires `drpcm-icon.png` to be the icon name.

**Comment by ThatOneCalculator** [comment]
@erickzhao Done!

**Review by erickzhao — APPROVED** [review]

**Comment by ThatOneCalculator** [comment]
Tysm @erickzhao ! How long does it usually take for it to appear in the list?

**Pull request merged**
