### PR TITLE
feat: add Boost Changer App to electron apps

### PR DESCRIPTION
**Pull request by nbebaw**
With this app you can control CPU turbo boost and the settings of the cpu speed in order to consuming less battery voltage on Linux. Boost Changer app made using Electron.
URL: https://github.com/nbebaw/boostchanger
Dashboard
About
settings

### CODE REVIEW

**Comment by nbebaw** [comment]
second commit for Semantic Pull Request

**Review by ckerr — COMMENTED** [review]
Hey @nbebaw, thank you for your application! As required in guidelines, your repository must be 20 days old, so I can't merge for the moment.

**Comment by nbebaw** [comment]
@ckerr Now my Repo is more than 20 days old

**Comment by Toinane** [comment]
Hey @nbebaw It's all good now! Thank you for your patience

**Pull request merged**
