### PR TITLE
feat: add Pragli

### PR DESCRIPTION
**Pull request by dsafreno**
Pragli is a virtual office for remote workers, built both for desktop with Electron and web.

It's closed source, so here's some screenshots as evidence:
Screen Shot 2019-10-15 at 11 42 58 AM
Screen Shot 2019-10-15 at 11 46 26 AM

Thanks!

### CODE REVIEW

**Comment by dsafreno** [comment]
@HashimotoYT @Sanjit1  - it looks like other apps are getting merged but we haven't been yet. Is there something I need to change about my PR?

**Comment by Sanjit1** [comment]
> @HashimotoYT @Sanjit1 - it looks like other apps are getting merged but we haven't been yet. Is there something I need to change about my PR?

Everything seems fine to me. I do not really work here, but @HashimotoYT does, so I'd wait for her to reply

**Comment by dsafreno** [comment]
Thanks Sanjit!

@HashimotoYT - awaiting your feedback here

**Comment by dsafreno** [comment]
@HashimotoYT Thank you!!

**Pull request merged**
