### PR TITLE
feat: Add Guilded

### PR DESCRIPTION
**Pull request by chevonc**
### Checklist

- [x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [x] My application is open-source and has been created for at least 20 days
- [x] My application is closed-source and here is a proof it uses Electron:

image

I think Guilded is a really popular chat app for eSports gamers and content creators. It's built on electron and would fit nicely into the app gallery

image

image

### CODE REVIEW

**Comment by chevonc** [comment]
@ckerr would you mind taking at look at this submission and merging if it looks good? Otherwise, what can I fix to get this merged

**Comment by Toinane** [comment]
Hey @chevonc sorry for the delay. Looks like your screenshot url redirect to a download image. You need to just show the image. Our build doesn't like this..

**Comment by chevonc** [comment]
@Toinane Sorry, just getting back to this. I've updated the url. Thanks for the feedback. 
Lmk if there's anything required for merging

**Comment by chevonc** [comment]
@ckerr I updated this PR to address the feedback. Would you mind taking a look and merging if everything looks good to you?

**Review by ckerr — APPROVED** [review]
LGTM. Thanks for the ping

**Review by ckerr — CHANGES_REQUESTED** [review]
@chevonc the content itself looks fine, but it looks like one of the CI tests is stalled indefinitely.

Let's kill two birds with one stone: if you rebase this to `master` and push, that will both be a fresher PR and ought to re-trigger the CI build test

**Comment by chevonc** [comment]
@ckerr I just rebased and pushed., Hopefully it runs this time. Lmk if there's anything else I can do from my end

**Pull request closed without merging**
