### PR TITLE
feat: add Create discord RPC

### PR DESCRIPTION
**Pull request by cenapyuce**
### Checklist

- [x] I have read and completed the checklist of [Submission Guide](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines)
- [ ] My application is open-source and has been created for at least 20 days
- [ ] My application is closed-source and here is a proof it uses Electron:

### Description

I don't want to take long. This app is an app that uses discord RPC.

How to use:
1. App ID
https://discord.com/developers/applications Here you can get the application id and write it.
2. Details
3. Status = Small text.
4.  
5. Download the file from rich presence> art and type the key provided.
6. The text that appears when you go above the 4th stage.

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @cenapyuce thanks for your pr and sorry for the last one! It's missing an app icon :)

**Comment by cenapyuce** [comment]
I can't commit, if I send you the photo, can you upload it?

photo: https://cenap.lifes-a-me.me/5uKY9Xa6l.png

**Review by ckerr — CHANGES_REQUESTED** [review]
@cenapyuce Thank you for the icon link, but please add the logo to your PR. It's not reasonable to ask @Toinane to fix your PR for you. :slightly_smiling_face:

**Review by ckerr — CHANGES_REQUESTED** [review]
- Please see https://github.com/electron/apps/blob/master/contributing.md#company-logos-and-names for information on how to use the name of someone else's software in a non-infringing way. The name "Discord RPC" will not be accepted, but something like "Canpyuce RPC for Discord" is more acceptable.

-  Could you provide more information to the description here? After reading it, I don't know any more than I did from reading the application name. "Rich presence" does not really describe what your application _does_.

All that said, thank you for the application submission! I look forward to seeing updates

**Comment by ThatOneCalculator** [comment]
Also, this seems very similar to https://www.electronjs.org/apps/drpcm

**Comment by cenapyuce** [comment]
> 

Both do the same job.

**Pull request closed without merging**
