### PR TITLE
feat: Add SnipCommand

### PR DESCRIPTION
**Pull request by gurayyarar**
Add "SnipCommand" App

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @gurayyarar thank you for your application!
As required in guideline, your repository is only 1day old and we need more than 20 days before accepting application.

**Comment by gurayyarar** [comment]
Hi, @Toinane 
Today is 20th day of added to application to this repo :) Do i need wait a couple of more days for publish?
Thanks.

**Comment by Toinane** [comment]
Hey @gurayyarar its now okay to merge :) thank you for the wait!

**Comment by gurayyarar** [comment]
@Toinane thank you so much :)

**Pull request merged**
