### PR TITLE
feat: add Motrix

### PR DESCRIPTION
**Pull request by agalwood**
Hi,

I am Dr_rOot, the author of Motrix. I open sourced the Motrix based on MIT License at Dec 19, 2018.

Motrix is a full-featured download manager that supports downloading HTTP, FTP, BitTorrent, Magnet, etc.

Motrix has a clean and easy to use interface. I hope you will like it.

### Screenshots
electron-apps-banner

screenshot-task-list-downloading-en@2x

motrix-preference-basic

motrix-preference-advanced

### Official Website:
<https://motrix.app/>

### GitHub Repository:
<https://github.com/agalwood/Motrix>

### Snapcraft
<https://snapcraft.io/motrix>

### CODE REVIEW

**Comment by agalwood** [comment]
Repository transfer done, and allowed : )

**Comment by HashimotoYT** [comment]
@agalwood Could you please allow edit this pull request for maintainers. You can do that in the pull request sidebar:

need edit rights

**Comment by agalwood** [comment]
I think I have encountered a bug on GitHub. I checked the allowed checkbox last time, but it is still unchecked. I just tested it again. After I checked it, I refreshed the page and the checked state was restored.

The following is an error report on the GitHub page console.

image

**Comment by agalwood** [comment]
I used Chrome Developer Tools to manually add the "js-status-indicator" class name to this checbox, and the checked was successful!

I think you can report this bug to your GitHub colleagues : )

**Pull request merged**
