### PR TITLE
feat: add Thermal app

### PR DESCRIPTION
**Pull request by mittalyashu**
Thermal: Git graphical interface for developers.

**Repository:** https://github.com/gitthermal/thermal
**Website:** https://thermal.codecarrot.net

### CODE REVIEW

**Comment by mittalyashu** [comment]
Thank you for merging this PR 👍🏻.

**Comment by codebytere** [comment]
@mittalyashu could you please rebase this?

**Comment by HashimotoYT** [comment]
@mittalyashu could you please rebase this?

**Comment by mittalyashu** [comment]
@HashimotoYT I have updated the branch with master.

**Comment by mittalyashu** [comment]
Thank you for merging the PR.

**Pull request merged**
