### PR TITLE
feat: add WizardMirror

### PR DESCRIPTION
**Pull request by Sanjit1**
### Wizard Mirror 

Hi all! This is my app called WizardMirror. It is an open-source app, that allows users to convert a Raspberry Pi into a cool mirror, and write apps for the mirror.
[Github Repo](https://github.com/Sanjit1/WizardMirror)
Screenshot

### CODE REVIEW

**Comment by Sanjit1** [comment]
I am a little bit confused about why Travis is still waiting. Do I need to make any changes or is there any issue, or do I need to fix something?

**Comment by Sanjit1** [comment]
Its almost been a month ...............

**Comment by HashimotoYT** [comment]
@Sanjit1 Please fix CI error:

```
1) human-submitted app data
       wizard-mirror
         icon
           is a square:

      AssertionError: expected 576 to equal 733
      + expected - actual

      -576
      +733
      
      at Context.<anonymous> (test/human-data.js:205:39)
```

**Comment by Sanjit1** [comment]
I had some weird stuff happen to my computer, so I will have to close this Pull Request and open a new one with the requested changes. Thank you all so much!

**Pull request closed without merging**
