### PR TITLE
feat: Update discord.yml

### PR DESCRIPTION
**Pull request by MaxTechnics**
Updating Discord's slogan from 'All-in-one voice, text and video chat for gamers' to 'Your place to talk' because of Discord's shift from Game chat to general communities.

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @MaxTechnics thank you for the update, can you edit the name commit with addind "feat: ...." ?

**Comment by MaxTechnics** [comment]
Like so?
I'm sorry it took so long

**Comment by Toinane** [comment]
No worries @MaxTechnics ! Its ok for the PR's title, but i need also the commit description to be edited, can you change it? sorry for that!

**Comment by MaxTechnics** [comment]
I think i got it changed. It seems needlessly complicated though. Tell me if that's good or not.

**Comment by MaxTechnics** [comment]
@Toinane, I noticed that 'this branch is out-of-date with the base branch', Should i press the update branch button?

**Comment by Toinane** [comment]
Yeah you can, but I can too, so no worries :) its now okay for me! Thank you!

**Pull request merged**
