### PR TITLE
feat: Pic crop added

### PR DESCRIPTION
**Pull request by ujw0l**

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @ujw0l thank you for your application but I can't add your app for now because your repo created 8 days ago.

> If you just created something, wait at least 20 days before submitting.

**Comment by ujw0l** [comment]
Sure, Is there anything I need to change until repo is 20 days old?

**Comment by Toinane** [comment]
> Sure, Is there anything I need to change until repo is 20 days old?

Not for now 👍

**Comment by Toinane** [comment]
Hey @ujw0l thank you for the wait! It's now good!

**Pull request merged**
