### PR TITLE
feat: Add app repomesh

### PR DESCRIPTION
**Pull request by raymondcrouch**

### CODE REVIEW

**Comment by raymondcrouch** [comment]
I am not sure what I am supposed to do now

**Comment by raymondcrouch** [comment]
mainscreen
settingsScreen

**Comment by raymondcrouch** [comment]
Renamed the yaml file to .yml

**Comment by raymondcrouch** [comment]
SCreenshot of main.js and package.json used by repomesh to show its built in Electron.

proofofelectronuse

**Comment by Toinane** [comment]
Hey there! Thank you for the application. It seems that it is no longer maintained or hasn't been updated for a long time, so i'll close this PR for now. Feel free to reopen it or make a new PR if needed.

**Comment by raymondcrouch** [comment]
Hi ,

Thanks for sending me this. I have been waiting for some time to hear about
this pull request.  I have tried to contact you guys but could not get a
response. What was wrong with my pull request? Was it waiting for me to do
something? I understood it was waiting for someone your side to approve. I
dont want it closed. I want it published. Please advise what I am doing
wrong so I can sort it out
.

**Comment by Toinane** [comment]
Hey @raymondcrouch sorry for the issue you had here, I'm a new helper here, the team is quite busy sometimes so sorry again! 
About your application, its look good to me!
Can I just know which version of Electron do you use? Thanks !

**Comment by Toinane** [comment]
I didn't receive any response from you @raymondcrouch yet. is it still on?

**Comment by raymondcrouch** [comment]
Sorry caught up in private stuff with kids having babies. the version of
electron being used is 7.1.3. You can see it referenced on the website at :
repomesh.com

Thanks for getting back. Sincere apologies for being tardy on this.

Best
Ray Crouch

**Comment by Toinane** [comment]
Hey @raymondcrouch no worries its okay! 👍 Thank you for your response, its now all good to me

**Comment by raymondcrouch** [comment]
Thankyou again for following up. 😉

**Pull request merged**
