### PR TITLE
feat: Add Arena

### PR DESCRIPTION
**Pull request by betseyliu**

### CODE REVIEW

**Comment by Toinane** [comment]
Hey @betseyliu thank you for your app submission!
Please, if your application is a closed source app, can you remove the "repository" field in the yaml and as per the [submission guidelines](https://github.com/electron/apps/blob/master/contributing.md#submission-guidelines), could you provide some evidence that this is an Electron app? [Previous PRs](https://github.com/electron/apps/pulls?utf8=%E2%9C%93&q=is%3Apr+evidence) are a good source for what other apps have used as evidence.

Also, I see your application don't support English language, so could you add the language field with your country code as per the [contributing locales](https://github.com/electron/apps/blob/master/contributing.md#locales)? And you can remove the "disabled: true" with the comment, this field is only used to hide discontinued application.

Thank you!

**Comment by betseyliu** [comment]
Hi @Toinane, 
 I have already fixed as required and what about this screenshot as an evidence?

**Comment by betseyliu** [comment]
> @betseyliu Would you please move forked repository from organization to the user account and allow editing this pull request from maintainers for easily reviewing.
> 
> need edit rights
@HashimotoYT  I have already moved the repository to my account and allowed editing this pull request from maintainers , thanks ~~

**Comment by Toinane** [comment]
Hey @betseyliu its now good! Thank you for your application 👍

**Pull request merged**
